# Generated by Django 3.2.9 on 2021-11-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='last_creator',
            new_name='last_editor',
        ),
    ]
