# Generated by Django 3.2.9 on 2021-11-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_rename_last_creator_candidate_last_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='scond_learning_ability',
        ),
    ]
