# Generated by Django 3.2.1 on 2021-11-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_candidate_scond_learning_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='adoctor_school',
        ),
        migrations.AddField(
            model_name='candidate',
            name='doctor_school',
            field=models.CharField(blank=True, max_length=125, verbose_name='博士生院校'),
        ),
    ]
