# Generated by Django 3.2.1 on 2021-11-27 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0005_alter_candidate_hr_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='first_interviewer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='hr_interviewer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='second_interviewer',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_interviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='一面面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_interviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='HR面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_interviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='二面面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='学习能力成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='专业能力成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9 >=9.0极优秀  8.0-8.9优秀  7.0-7.9良好  6.0-6.9一般  <=5.9较差', max_digits=2, null=True, verbose_name='初试成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_score',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='S极优秀  A优秀  B良好  C一般', max_length=10, verbose_name='HR复试综合等级'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='paper_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='00.0-99.9', max_digits=3, null=True, verbose_name='笔试成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_communication_ability',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='沟通能力成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='学习能力成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_pressure_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='抗压能力成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='专业能力成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_pursue_of_excellence',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9', max_digits=2, null=True, verbose_name='追求卓越成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0-9.9 >=9.0极优秀  8.0-8.9优秀  7.0-7.9良好  6.0-6.9一般  <=5.9较差', max_digits=2, null=True, verbose_name='专业复试成绩'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='test_score_of_general_ability',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='00.0-99.9', max_digits=3, null=True, verbose_name='综合能力评测成绩'),
        ),
    ]
